# Findomain configuration file. The following listed values are all the possible values you can set at the moment.
# IF YOU ARE NOT USING ONE OF THEM PLEASE LEAVE THIS EMPTY OR DELETE IT FROM THE FILE

#postgres_connection = "Your postgres connection URI here in the following format: postgresql://user:password@host:port/database"
#discord_webhook = "Your Discord webhook URL here"
#slack_webhook = "Your Slack webhook URL here"
#telegrambot_token = "Your Telegram bot token here"
#telegram_chat_id = "Your Telegram chat ID here"
#spyse_token = "Your Spyse bearer tokens here, please use comma to separate if multiple are added."
fb_token = "0534d808258600f5ff90e1240305112a"
virustotal_token = "250296edb15ec67087cdd5a1002dc6198d9cc73578e7c419c0de86d4994dcf60"
securitytrails_token = "vhVUvPNOlRnzULVPmTtLmg9UjwJCWbek"
#certspotter_token = "Your CertSpotter bearer tokens here, please use comma to separate if multiple are added."
#c99_api_key = "Your C99.nl API keys here, please use comma to separate if multiple are added."
#threads = "Number of threads here"
#rate_limit = "Number of seconds for the rate limit here"
#http_timeout = "Value in seconds for the HTTP Status check of subdomains. Default 5."
#dbpush_if_timeout = "Enable --mtimeout flag. Possible values: true, false"
#no_monitor = "Enable --no-monitor flag. Possible values: true, false"
#randomize = "Randomize the order of the targets instead of sorting them alphabetically"
#user_agents_file = "Path to user agents file"
#exclude_sources = "List of sources to exclude separated by comma"
